[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.core = esp32
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; Sobrecarrega a definição interna sem gerar aviso de redefinição
build_unflags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1

build_flags = 
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_MODE_OCT=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -I src/ui

lib_deps = 
    lvgl/lvgl@^8.4.0
    lovyan03/LovyanGFX@^1.2.30
    adafruit/Adafruit MLX90614 Library @ ^2.1.5